# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitySeansonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=200)),
                ('storeID', models.CharField(max_length=200)),
                ('citySeansonInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.CitySeansonInfo')),
            ],
        ),
    ]
