# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20161122_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='storeID',
            new_name='store_id',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='storeName',
            new_name='store_name',
        ),
    ]
