# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_auto_20161124_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRatings',
            new_name='Ratings',
        ),
    ]
